routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    $routeName = auth()->user() && (auth()->user()->is_mahasiswa || auth()->user()->is_dosen) ? 'admin.calendar.index' : 'admin.home'; 
    if (session('status')) {
        return redirect()->route($routeName)->with('status', session('status'));
    }

    return redirect()->route($routeName);
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Time Entries
    Route::delete('time-entries/destroy', 'TimeEntriesController@massDestroy')->name('time-entries.massDestroy');
    Route::get('time-entries/show-current', 'TimeEntriesController@showCurrent')->name('time-entries.showCurrent');
    Route::post('time-entries/update-current', 'TimeEntriesController@updateCurrent')->name('time-entries.updateCurrent');
    Route::resource('time-entries', 'TimeEntriesController');

    // Lessons
    Route::delete('lessons/destroy', 'LessonsController@massDestroy')->name('lessons.massDestroy');
    Route::resource('lessons', 'LessonsController');

    // School Classes
    Route::delete('college-classes/destroy', 'CollegeClassesController@massDestroy')->name('college-classes.massDestroy');
    Route::resource('college-classes', 'CollegeClassesController');

    Route::get('calendar', 'CalendarController@index')->name('calendar.index');

    // Reports
    Route::get('reports', 'ReportsController@index')->name('reports.index');
});

app/Http/Controllers/Admin/CollegeClassesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCollegeClassRequest;
use App\Http\Requests\StoreCollegeClassRequest;
use App\Http\Requests\UpdateCollegeClassRequest;
use App\CollegeClass;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CollegeClassesController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('college_class_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $collegeClasses = CollegeClass::all();

        return view('admin.collegeClasses.index', compact('collegeClasses'));
    }

    public function create()
    {
        abort_if(Gate::denies('college_class_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.collegeClasses.create');
    }

    public function store(StoreCollegeClassRequest $request)
    {
        $collegeClass = CollegeClass::create($request->all());

        return redirect()->route('admin.college-classes.index');
    }

    public function edit(CollegeClass $collegeClass)
    {
        abort_if(Gate::denies('college_class_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.collegeClasses.edit', compact('collegeClass'));
    }

    public function update(UpdateCollegeClassRequest $request, CollegeClass $collegeClass)
    {
        $collegeClass->update($request->all());

        return redirect()->route('admin.college-classes.index');
    }

    public function show(CollegeClass $collegeClass)
    {
        abort_if(Gate::denies('college_class_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $collegeClass->load('classLessons', 'classUsers');

        return view('admin.collegeClasses.show', compact('collegeClass'));
    }

    public function destroy(CollegeClass $collegeClass)
    {
        abort_if(Gate::denies('college_class_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $collegeClass->delete();

        return back();
    }

    public function massDestroy(MassDestroyCollegeClassRequest $request)
    {
        CollegeClass::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/collegeClasses/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.collegeClass.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.college-classes.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.collegeClass.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.collegeClass.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/collegeClasses/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.collegeClass.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.college-classes.update", [$collegeClass->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.collegeClass.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $collegeClass->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.collegeClass.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/collegeClasses/index.blade.php
@extends('layouts.admin')
@section('content')
@can('college_class_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.college-classes.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.collegeClass.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.collegeClass.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-CollegeClass">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.collegeClass.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.collegeClass.fields.name') }}
                        </th>
                        <th>
                            Schedule
                        </th>
                        <th>
                        {{ trans('cruds.collegeClass.fields.action') }} &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($collegeClasses as $key => $collegeClass)
                        <tr data-entry-id="{{ $collegeClass->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $collegeClass->id ?? '' }}
                            </td>
                            <td>
                                {{ $collegeClass->name ?? '' }}
                            </td>
                            <td>
                                <a href="{{ route('admin.calendar.index') }}?class_id={{ $collegeClass->id }}">View Schedule</a>
                            </td>
                            <td>
                                @can('college_class_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.college-classes.show', $collegeClass->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('college_class_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.college-classes.edit', $collegeClass->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('college_class_delete')
                                    <form action="{{ route('admin.college-classes.destroy', $collegeClass->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('college_class_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.college-classes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-CollegeClass:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/collegeClasses/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.collegeClass.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.college-classes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.collegeClass.fields.id') }}
                        </th>
                        <td>
                            {{ $collegeClass->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.collegeClass.fields.name') }}
                        </th>
                        <td>
                            {{ $collegeClass->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.college-classes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header">
        {{ trans('global.relatedData') }}
    </div>
    <ul class="nav nav-tabs" role="tablist" id="relationship-tabs">
        <li class="nav-item">
            <a class="nav-link" href="#class_lessons" role="tab" data-toggle="tab">
                {{ trans('cruds.lesson.title') }}
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#class_users" role="tab" data-toggle="tab">
                {{ trans('cruds.user.title') }}
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" role="tabpanel" id="class_lessons">
            @includeIf('admin.collegeClasses.relationships.classLessons', ['lessons' => $collegeClass->classLessons])
        </div>
        <div class="tab-pane" role="tabpanel" id="class_users">
            @includeIf('admin.collegeClasses.relationships.classUsers', ['users' => $collegeClass->classUsers])
        </div>
    </div>
</div>

@endsection